function [T]=FK_2(Tbase,Ttool,d,q,t,l)

T=Tbase*Ty(d)*Ty(t(1))*Ry(q(1))*Tz(l(1))*Tx(t(2))...
    *Ty(t(3))*Tz(t(4))*Rx(t(5))*Ry(t(6))*Rz(t(7))...
    *Ry(q(2))*Tz(l(2))*Tx(t(8))*Ty(t(9))*Tz(t(10))...
    *Rx(t(11))*Ry(t(12))*Rz(t(13))*Ry(q(3))*Ttool;