function [T]=FK_3(Tbase,Ttool,d,q,t,l)

T=Tbase*Tx(d)*Tx(t(1))*Rx(q(1))*Ty(l(1))*Tx(t(2))...
    *Ty(t(3))*Tz(t(4))*Rx(t(5))*Ry(t(6))*Rz(t(7))...
    *Rx(q(2))*Ty(l(2))*Tx(t(8))*Ty(t(9))*Tz(t(10))...
    *Rx(t(11))*Ry(t(12))*Rz(t(13))*Rx(q(3))*Ttool;